{% set name = "microbench" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alubbock/microbench/archive/v{{ version }}.tar.gz
  sha256: fba16c30e5b49a9f807950f8243243897af3c7f5ce0bec9dd45391b503aa35f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - microbench
  commands:
    - pip check
    - ls
    - pytest microbench/tests/
  source_files:
    - .
  requires:
    - pip
    - pytest
    - pandas
    - line_profiler
    - psutil
    - python {{ python_min }}

about:
  home: https://github.com/alubbock/microbench
  summary: Micro-benchmarking framework. Extensible, with distributed/cluster support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
